id: amd64-steamdeck
arch: amd64
firmware: efi
packages:
  - linux-image-amd64
notes:
  - "Default profile compatible"
features:
  lora: false
  haptics: false
  sensors: false
  camera: auto
  ai_ml: auto
  media: auto
