id: armhf-legacy
arch: armhf
firmware: uboot
packages:
  - linux-image-armhf
notes:
  - "Experimental legacy"
features:
  lora: false
  haptics: false
  sensors: false
  camera: auto
  ai_ml: auto
  media: auto
